#!/usr/bin/env python3
import argparse
import webview
import pyautogui as pag
from subprocess import run, PIPE
from pynput.keyboard import Listener, Key

def on_press(key):
    if key == Key.esc:
        window.destroy()
        return False

pos = pag.position()
width, height = pag.size()

parser = argparse.ArgumentParser(description='Search selected text online')

parser.add_argument('-f', '--frameless', action='store_true', help='Makes the window frameless')
parser.add_argument('-s', '--selectable', action='store_true', help='Allow text selection')

args = parser.parse_args()

clip_text = run(['xclip', '-o'], stdout=PIPE).stdout.decode('utf-8')

window = webview.create_window('Dictionary',
                      url=f'https://www.google.com/search?q=define {clip_text}#search',
                      width=width * 0.5, height=height * 0.4, x=pos.x, y=pos.y, resizable=True,
                      fullscreen=False, frameless=args.frameless, on_top=True, text_select=args.selectable)

with Listener(on_press=on_press) as listener:  # Create an instance of Listener
    webview.start()
    listener.join() 
